### ISSUE TITLE
[fetch] 在后端使用的时候会出现莫名其妙的错误

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#102]
## 描述

具体原因还未知，触发的方式是

fetch的参数带有 { query: { a: 1} }

只要 query 有值，就会报奇怪的错误

调用

```
    const result = await sdk.vehicle.listRecords({
      vehicleId: "xxxx",
      query: { a: "a" },
    });
```

```
      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.it (src/index.test.js:11:3)
      at Object.describe (src/index.test.js:5:1)
```

猜测：

和 fetch 库里自己写的 stringfiy  有关系

**Comment by zzswang** [comment]
不是 fetch 的原因。

是 json-server 的 rewrite 规则的问题。
